### PR TITLE
[CI-12707] Update CI arch diagram

### PR DESCRIPTION
**Pull request by brian-r-fisher**
Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: Update CI arch diagram
* Jira/GitHub Issue numbers (if any): CI-12707
* Preview links/images (Internal contributors only): https://6662762c51250da723ba52fc--harness-developer.netlify.app/docs/continuous-integration/get-started/overview#harness-ci-architecture

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [x] Successful preview build.
- [x] Code owner review.
- [x] No merge conflicts.
- [x] Release notes/new features docs: Feature/version released to at least one prod environment.

### CODE REVIEW

**Review by hemanthmantri — DISMISSED** [review]
Harness Cloud shouldn't be in the "Build Infra" box here. Harness cloud infra is with Harness side of the network.

**Comment by tkouhsari-harness** [comment]
Not sure I understand the difference between "Build Responses" and "Build Details". "Build Dependencies" is duplicated on the right.

**Comment by tkouhsari-harness** [comment]
> Harness Cloud shouldn't be in the "Build Infra" box here. Harness cloud infra is with Harness side of the network.

Should the Hosted Builds architecture diagram be completely separate?

**Comment by brian-f-harness** [comment]
@hemanthmantri @tkouhsari-harness What do we need to update so we can merge the PR?

**Comment by tkouhsari-harness** [comment]
> @hemanthmantri @tkouhsari-harness What do we need to update so we can merge the PR?

I believe that we should have a separate architectures for hosted builds. I don't think that's my call though.

**Review by nofarblue — APPROVED** [review]
looks good

**Comment by nofarblue** [comment]
this image is used by this page https://developer.harness.io/docs/continuous-integration/get-started/overview
Under the architecture we we can have tabs for Cloud vs self-managed and have the relevant diagram in each @hemanthmantri @brian-f-harness

**Review by dewan-ahmed — APPROVED** [review]
Cleaning up old PRs. Merging based on approval from @nofarblue

**Pull request merged**
