### PR TITLE
adding s3fs to s3 artifacts doc

### PR DESCRIPTION
**Pull request by jimsheldon**
Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

### CODE REVIEW

**Comment by jimsheldon** [comment]
The new section is here https://6643b5cf6edc7d053921fc64--harness-developer.netlify.app/docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-s3#use-s3fs-fuse

**Review by Ompragash — APPROVED** [review]
LGTM

**Comment by jimsheldon** [comment]
Latest changes https://6644c32bfeaff9237ff017c2--harness-developer.netlify.app/docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-s3#use-s3fs-fuse

**Review by dewan-ahmed — APPROVED** [review]
LGTM

**Pull request merged**
