### PR TITLE
HDH  217 post ds upgrade rss feed not rendering

### PR DESCRIPTION
**Pull request by rohanmaharjan100**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by ravilach** [comment]
@rohanmaharjan100 thanks for the help. We downgraded to DS 3.0.1. This does get us ready post 3.1.0. Can we validate the fix in 3.0.1? Currently we are stable in 3.0.1.

**Comment by rohanmaharjan100** [comment]
@ravilach  E
Everything seems to be stable. I guess only concern would be the build time.

**Comment by ravilach** [comment]
@rohanmaharjan100 can we check this fix against 3.0.1 please? If it works in 3.0.1 would assume it works in 3.1+. Let's not upgrade to 3.1 in this PR please.

**Comment by rohanmaharjan100** [comment]
Sure !

**Review by ravilach — APPROVED** [review]

**Pull request merged**
