### PR TITLE
 HDH-232-roadmap-improvements

### PR DESCRIPTION
**Pull request by rohanmaharjan100**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [x] *Optional* Screenshot.

### CODE REVIEW

**Review by ravilach — APPROVED** [review]
LGTM

**Comment by ravilach** [comment]
@rohanmaharjan100 let us know when you are good to go, can merge.

**Comment by rohanmaharjan100** [comment]
@ravilach  i am looking to add read time of the linked document to the card. If that is not need , it is good to merge.

**Comment by ravilach** [comment]
Thanks @rohanmaharjan100 it is not needed.

**Pull request merged**
