### PR TITLE
Doc 2694 cd left nav update

### PR DESCRIPTION
**Pull request by michaelcretzman**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* https://harness.atlassian.net/browse/DOC-2694

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by ravilach** [comment]
@michaelcretzman this is a big one. Was looking at the preview link before the latest commit and was looking good. Though last commit maybe some items have shuffled around and build failed on missing images. 

@KimberlyFields / @michaelcretzman since such a large change, maybe good to get another Docs Team Member to review also?

-Ravi

**Comment by ravilach** [comment]
Tested a few re-directs on https://643850ea73f54007b45dbcdb--harness-developer.netlify.app and looks good to me.

**Comment by ravilach** [comment]
Tested a few re-directs on https://643850ea73f54007b45dbcdb--harness-developer.netlify.app and looks good to me.

**Review by ravilach — APPROVED** [review]
Might also be helpful to get another reviewer. Thanks for the re-org!

**Comment by michaelcretzman** [comment]
from Kim: I think there will need to be a few tweaks post-merge, but go ahead and merge this to get it out of the way. I'll provide feedback about the tweaks in a Jira ticket.

**Pull request merged**
