### PR TITLE
[DOC-3687] SMP 0.9.0, 802xx release notes

### PR DESCRIPTION
**Pull request by brian-f-harness**
SMP 802xx release notes

For reviewers, previews are available.

[Harness Self-Managed Enterprise Edition Release Notes (NextGen)](https://6508d31d25bea365689fd4ba--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition)

[Harness Self-Managed Enterprise Edition Release Notes (FirstGen)](https://6508d31d25bea365689fd4ba--harness-developer.netlify.app/docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes)

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by akshay-khole** [comment]
@brian-f-harness  these are release notes only , correct? 
Few of the smp release notes like chart migration are missing 
we will have a separate document for smp features like DR?

**Comment by brian-f-harness** [comment]
> @brian-f-harness these are release notes only , correct? Few of the smp release notes like chart migration are missing we will have a separate document for smp features like DR?

@akshay-khole Yes, this PR is for release notes only. Doc updates will be handled separately. Is there a list of SMP tickets available? They are normally outside of Faruk's filter.

**Comment by akshay-khole** [comment]
@arya-harness  @saitejavn-harness  will share ticket details for chart migration issues 
@swapnil-harness  for all DR and DB related issues

**Comment by brian-f-harness** [comment]
Closed in favor of https://github.com/harness/developer-hub/pull/3548

**Pull request closed without merging**
