### PR TITLE
feat: embed auto-generated card list to docs landing pages [HDH-110]

### PR DESCRIPTION
**Pull request by wei-harness**
used Feature Flags Docs landing page as a sample

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [x] *Optional* Screen Shoot. 
Screen Shot 2023-04-13 at 3 12 46 PM
Screen Shot 2023-04-13 at 3 12 16 PM

### CODE REVIEW

**Comment by ravilach** [comment]
@wei-harness will review.

**Comment by StrawberryPad** [comment]
@ravilach I really don't understand what this PR is doing. Is there anything specific you want me to check? I see it has something to do with landing pages, but I don't understand any details of any of these file changes. I'm curious about the commented block in sidebars.js. What is that for?

**Comment by ravilach** [comment]
@StrawberryPad was more of a prototype on how something could look on a landing page. @wei-harness can stash the FF changes and implement the card only changes, most likely will close this PR and raise another, keeping this branch for a later date.

**Comment by ravilach** [comment]
@wei-harness this was already merged in, in a different PR. Closing.

**Pull request closed without merging**
