### PR TITLE
cv docs restructure

### PR DESCRIPTION
**Pull request by SudheendraKatte**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by SudheendraKatte** [comment]
Hi @ravilach , this PR is for restructuring of CV docs left nav. As part of the reorg, I have also rewritten the generic topic. Please review and provide your views.

**Comment by ravilach** [comment]
Will review on https://644133f108511d2902f264c8--harness-developer.netlify.app/

**Comment by ravilach** [comment]
Looks good, can we make sure https://github.com/harness/developer-hub/pull/1349 is included also @SudheendraKatte? Thanks!

**Comment by SudheendraKatte** [comment]
@ravilach , created a separate branch and pr (https://github.com/harness/developer-hub/pull/1385) for merging reorg changes from this PR and the changes from PR https://github.com/harness/developer-hub/pull/1349.

**Pull request closed without merging**
