### PR TITLE
Create upload-dotnet-to-azure-artifacts.md

### PR DESCRIPTION
**Pull request by Ompragash**
Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

### CODE REVIEW

**Comment by dewan-ahmed** [comment]
Hi @Ompragash thanks for this PR. From the initial wording "Use the **Build, Push, and Deploy .NET Packages** steps", it seems that there's a native step to do this as we have for JFrog. But since this is a combination of **run** steps, we can reword accordingly. 

I'm reviewing this PR.

**Comment by Ompragash** [comment]
> it seems that there's a native step to do this as we have for JFrog.

in CI? we have a native connector of type "Azure Artifacts" but it can used with CD Deploy stage and this doc outlines the steps for CI using `Run Step`
Screenshot 2024-07-31 at 7 44 07 PM

**Comment by nofarblue** [comment]
@Ompragash  made some changes per review comments. please review.

**Comment by Ompragash** [comment]
Thanks @nofarblue! It looks good! just added back the info on secrets to guide the users.

**Comment by dewan-ahmed** [comment]
Hi @Ompragash I've reviewed and pushed some changes as editorial fixes via https://github.com/harness/developer-hub/pull/7414/commits/110afb3344b0d4c8319733529d2bdc41bd007cfe

I have one question. You have the following sentence towards the end of the doc:

> The Build, Package, and Push .NET Packages steps have the following settings 

But there are no settings mentioned. Do we need to add some settings here or link to a page that has these settings?

**Review by dewan-ahmed — APPROVED** [review]
Thanks for this contribution @Ompragash

**Pull request merged**
