### PR TITLE
Ng delegate node reorg doc 2421

### PR DESCRIPTION
**Pull request by kat-enos**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ x ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ x] Tested Locally - The re-organized node builds locally before and after the application of the redirects file. The redirects for which the page location in HelpDocs was not changed during the migration were tested by using the "from" link beginning with "docs". The redirects for which the page location in HelpDocs was changed during migration were tested by opening the HelpDocs application and looking at the page location in the hierarchy. All the redirects now work. Along the way, it was determined that there is some case-sensitivity in how the redirect links are constructed; the casing issue was corrected. Further changes for developmental, line and copyedits are slated for after the debut of the revised documentation hierarchy. This will help to simplify the complexity of getting this project out the door with as few merge issues as possible.
- 
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Review by KimberlyFields — CHANGES_REQUESTED** [review]
@kat-enos the new left nav structure does not match the outline that we agreed to use (Prateek's outline). Install delegates is not in the right place, there's still a delegate guide section, the delegate image type topic is not near the top (at Sri requested), etc. Please take another look at the outline and update the left nav accordingly.

**Review by ravilach — APPROVED** [review]
From the redirect side looks good to me.

**Comment by KimberlyFields** [comment]
@pratmit and @kat-enos I think a few items in the Get started with delegates section may be misplaced.

Screen Shot 2023-01-19 at 9 36 18 AM

- Build custom delegate images with third-party tools - Is this subject more suited to the Customize delegates or Configure delegates section? It doesn't seem like introductory info. 
- Delegate auto-update - Same question as above.
- Delegate how-to - Let's get rid of that topic. I don't think we need to list all of the procedures for delegates. It could become unruly as the content grows. 
- Delegate image types - I think this should be higher in the TOC. I suggest below Delegate overview. 
- Enable root privileges to add custom binaries - Is this subject more suited to the Customize delegates or Configure delegates section? It doesn't seem like introductory info. 
- Install delegates with third-party tools - Should this be in the Advanced installation section?
- Support for Docker delegate images - This comment is not about the location of this topic in the TOC so it's outside of the purpose of this PR, but it's something to consider. The title doesn't seem to match the content of the topic. Should it be more specific, such as "Image tags and client libraries for delegates"?

**Comment by kat-enos** [comment]
Thanks @Ravi.

**Comment by kat-enos** [comment]
@KimberlyFields With the exception of your bulleted item 3, these topics are placed in accord with the GoogleDocs page at  @pratmit's comments in https://harness.atlassian.net/browse/DOC-2421. 

Re your concern about whether certain topics belong in a section on customization or installation, this is why I advocate a more typical developer guide structure like what I proposed at https://docs.google.com/document/d/1ZxhGUeZM73-VkuqGuDOwAhsCmrQLrZAdzCR4RO1AACQ/edit, a structure that does not require readers to figure out how we categorize the content and doesn't require us to decide whether customization of an installation process is an installation or customization topic. 

Re the list of how-to topics, no instruction was given on them and I had planned to delete the page and to provide a useful landing/technology page providing information about delegate version, quick links to release notes, and offering "paths" through the documentation, for example, a list of topics to read when you're learning versus a list of topics to read when you're considering automating installation. This can complement a ToC and make it easier to point out new or changed content as well as any alerts.

I believe the placement of these topics in an introductory or overview section is appropriate since they provide basic information about delegates and what you can do with them and are less procedural and more general. Information about type and kind is also considered basic information so I believe the topic on image types should be included in that basic information about delegates that the overview/introduction area provides. My plan for these topics is to developmentally edit the information into different topics where necessary and give the topics more transparent names. This I intended to do in a second developmental pass after the basic top-level changes are made to the ToC.

I suggest we run with the improvements specified in the GoogleDoc and in @pratmit's comments in the ticket. Deletion of the list of how-to topics probably won't break a lot of links or take a lot of time to repair and the revised structure basically echos the categorization of topics on that page anyway, so deleting that page now would have little impact. This way the improvements we've got can do some good right now and path is clear for the global path changes that Doug said he hoped to get done this week. Continued changes and the need to validate them and support links to them across the docset will put any deployment into next week and mean more issues with PR merges. 

Thanks.

**Comment by KimberlyFields** [comment]
@kat-enos and @pratmit I'll approve the PR for the sake of getting these initial changes in, but I'd like us to revisit the Get started section as soon as possible.

**Review by KimberlyFields — APPROVED** [review]

**Pull request merged**
