### PR TITLE
CI 1.32 release notes draft CI-13135

### PR DESCRIPTION
**Pull request by douglas-j-bothwell**
### Preview link

- CI release notes > [Version 1.32](https://6679a5c3e907430e747a72fa--harness-developer.netlify.app/release-notes/continuous-integration#version-132)

### Merge requirements

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

### CODE REVIEW

**Review by nofarb — APPROVED** [review]
lgtm

**Review by nofarblue — APPROVED** [review]

**Comment by dewan-ahmed** [comment]
Resolved conflicts. Awaiting a review from @nofarblue before merging.

**Comment by dewan-ahmed** [comment]
Hi @lkilpatrick-harness could you please create a new PR for CI 1.32 release notes? Douglas raised this PR https://github.com/harness/developer-hub/pull/7176/files before he left, but it was never merged. I can resolve the merge conflicts and merge but I wanted to get you some PR merge practice for release notes. Here's what you have to do:

1. Make sure your fork of HDH is up to date.
2. Create a new branch.
3. Ensure the changes are not present in past or future release notes.
4. Copy the changes from https://github.com/harness/developer-hub/pull/7176/files in respective places.
5. Raise PR.

This shouldn't take long. Thanks.

**Review by jenniferopal — APPROVED** [review]
lgtm!

**Comment by dewan-ahmed** [comment]
Thanks for working on this backlog issue @jenniferopal 
The change has been merged via https://github.com/harness/developer-hub/pull/7648
Hence, closing this PR.

**Pull request closed without merging**
