### PR TITLE
chore: Update Hero animation [HDH-161]

### PR DESCRIPTION
**Pull request by wei-harness**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [x] *Optional* Screen Shoot. 

Screen Shot 2023-07-19 at 10 12 44 PM

### CODE REVIEW

**Comment by wei-harness** [comment]
Preview URL: https://64b855b1cbdc5500ac0c86e4--harness-developer.netlify.app

**Comment by ravilach** [comment]
Looks good to me, prob our ESLint Check did not work since we introduced new packages? @wei-harness. We should remove the ESlint and textlint GHAS checks at this point.

**Comment by ravilach** [comment]
Looking back at ESLint, did catch something..

image

**Comment by wei-harness** [comment]
@ravilach updated the .eslintignore file to avoid the check for lottie json

**Comment by wei-harness** [comment]
@ravilach for now all the DocButton are without tooltip property by default, feel free to let the md owners to add a tooltip="..." property if needed.

**Comment by ravilach** [comment]
Validated on mobile. LGTM.

**Review by ravilach — APPROVED** [review]

**Pull request merged**
