### PR TITLE
feedback component in all pages

### PR DESCRIPTION
**Pull request by rohanmaharjan100**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [
image
 ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by aimurphy** [comment]
Just my two cents on this: There is a lot of text for just a feedback request, and with multiple sections we risk people closing the dialog before they've submitted their comment.

I think we could do something more simplistic, like this but without the rating:

image

* "Let us know what you think about the Harness Developer Hub."
* "Comment *" field (required).
* "Email (optional)" field.
* "Submit" button.

After they click submit, show a simple "Thank you for your feedback." message with a "Close" button.

**Comment by ravilach** [comment]
@aimurphy that feedback form out of the box for what we use in product. @rohanmaharjan100 just for the PR as we discussed in Slack, would be better below the `edit page` link. Thanks!

**Comment by ravilach** [comment]
image

**Comment by ravilach** [comment]
@rohanmaharjan100 per our convo this AM, looks like the feedback item is missing off the homepage. Thanks!

**Review by ravilach — APPROVED** [review]

**Pull request merged**
