### PR TITLE
Update docker-delegate-to-ecs-fargate.md with Terraform module reference

### PR DESCRIPTION
**Pull request by rssnyder**
For reviewers, [a preview](https://645a9c642083c3235f5a3b4b--harness-developer.netlify.app/docs/platform/Delegates/install-delegates/docker-delegate-to-ecs-fargate) is available.

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Review by brian-f-harness — DISMISSED** [review]

**Review by pratmit — DISMISSED** [review]
LGTM

**Comment by brian-f-harness** [comment]
@rssnyder A question came up from @michaelcretzman during peer review:

On line 292:

image

**Comment by rssnyder** [comment]
> @rssnyder A question came up from @michaelcretzman during peer review:
> 
> On line 292:
> 
> image

I am the maintainer of the module.

I wrote the module to force users to keep the token (as it is sensitive) in AWS secrets manager, since ECS has native support for using secrets in ENV if they are in secrets manager.

**Comment by brian-f-harness** [comment]
> > @rssnyder A question came up from @michaelcretzman during peer review:
> > On line 292:
> > image
> 
> I am the maintainer of the module.
> 
> I wrote the module to force users to keep the token (as it is sensitive) in AWS secrets manager, since ECS has native support for using secrets in ENV if they are in secrets manager.
> 
> additionally, why can I not see his comment on this PR?

Thank you for the clarification.

I committed a fix for a typo during his review. I'm not sure why his comments don't show, but maybe the timing of my commit affected his review? (I will hold off on adding commits during future reviews.) 

Thanks again.

**Pull request merged**
