### PR TITLE
Refactor CI Tutorials

### PR DESCRIPTION
**Pull request by ravilach**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

Duplicate PR since original PR had lots of MCs. 

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [x] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by ravilach** [comment]
image

**Comment by aimurphy** [comment]
@ravilach the preview build failed.

**Comment by ravilach** [comment]
@aimurphy got it fixed. Will work with @schoudhury to iterate on the structure. Got the PR in a mergeable state. 
https://642fa0a62836db5b7cb7b341--harness-developer.netlify.app/

**Review by aimurphy — APPROVED** [review]
lgtm, thanks

**Comment by ravilach** [comment]
Thanks. Will push this version in and continue to iterate.

**Pull request merged**
