### PR TITLE
HDH-163-adjust-padding-in-top-nav

### PR DESCRIPTION
**Pull request by rohanmaharjan100**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [
image
image

-  ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by rohanmaharjan100** [comment]
@ravilach Please review. Thank you

**Comment by ravilach** [comment]
@rohanmaharjan100 can we keep the search icon and make the search box slightly wider? 

image

**Comment by rohanmaharjan100** [comment]
hmm, Please let me know what should i do after taking  look at preview build. @ravilach

**Comment by ravilach** [comment]
Looks fine to me in the preview. 

https://64bfe1e1407ef10caafbbf03--harness-developer.netlify.app/

image

**Review by ravilach — APPROVED** [review]

**Pull request merged**
