### PR TITLE
HDH-295-remote-api-call-c-url-plugin-for-hdh-dynamic-material

### PR DESCRIPTION
**Pull request by rohanmaharjan100**
Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \_______
image
___________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

### CODE REVIEW

**Comment by ravilach** [comment]
Looks like the build failed, I wonder if we can wrap like DS is saying.

```
 It looks like you are using code that should run on the client-side only.

        To get around it, try using one of:

        - `<BrowserOnly>` (https://docusaurus.io/docs/docusaurus-core/#browseronly)

        - `ExecutionEnvironment` (https://docusaurus.io/docs/docusaurus-core/#executionenvironment).

        It might also require to wrap your client code in `useEffect` hook and/or import a third-party library dynamically (if any).
```

**Comment by ravilach** [comment]
Maybe one approach: https://github.com/harness/developer-hub/pull/7556/files

**Comment by ravilach** [comment]
@rohanmaharjan100 thanks for making progress. In the preview domain (https://66bb24de9028aecfbb537232--harness-developer.netlify.app/docs/hdh/hdh-docusaurus-sandbox/#hdh-api-call) the fall back address is present in all the calls.

image

Possibly the staging domain does not go through our "proxy"'configuration or Safari blocking the call?

Thanks!

**Comment by rohanmaharjan100** [comment]
Proxy doesnot work on staging

**Review by ravilach — APPROVED** [review]
Can merge and see on Prod. Low risk since only on sandbox page.

**Pull request merged**
