### PR TITLE
Refactor of CI Tutorials

### PR DESCRIPTION
**Pull request by ravilach**
Refactor of CI Tutorial

* Created new Tutorial Landing Pages and Categories
* Created re-directs of old locations 
* Updated all cards for CI
* Tidy updated "all tutorials" for CD

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

Partial Refactor of CI and updated CI All Tutorials. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [x] *Optional* Screen Shoot. 

image

### CODE REVIEW

**Comment by ravilach** [comment]
image

**Comment by ravilach** [comment]
Have a few Merge Conflicts to resolve. Once we like the new set-up:
https://642f29d7c0d0ad006a5acc46--harness-developer.netlify.app/tutorials/build-code/test/saucelabs-proxy

**Review by aimurphy — APPROVED** [review]
approved w just one request: Please move "Get started for free..." to the top of the TOC, above "Build".

**Comment by ravilach** [comment]
Made a new PR to resolve the MCs. Will close this PR: 
https://github.com/harness/developer-hub/pull/1243

**Pull request closed without merging**
