### PR TITLE
Hdh left nav redesign tutorial unification

### PR DESCRIPTION
**Pull request by aimurphy**
Tutorial unification

## Objective

Combine Tutorials with Documentation. Remove Tutorials from top nav/left nav.

Content was moved from Tutorials to either:
* A Tutorials folder in the module's documentation section.
   * **Tutorials moved in this way require further analysis by the module's writer to move them to more appropriate locations (eg. Get started or some other place).**
   * Ultimately, there should be no distinction between tutorials and regular docs. A tutorial is either 1) Get started (a step-by-step guide showing a beginner flow for new users) or 2) Task/Process (step-by-step instructions showing how to achieve some use case).
* Alongside related content in the module's documentation (Some of this was based on my knowledge of the modules/docs and some writers provided input about where they wanted the content to go for their module.)

Content might have been removed or edited for the following reasons:
* Duplicates (or near duplicates) of existing Documentation pages
* Style guide compliance issues
* Syntax/rendering issues

Please direct questions about this project to #documentation.

## Home page

https://65d4cfa04fa67d001df56700--harness-developer.netlify.app/ 

image

## CI

Already moved

## CD

15 tutorials about Deployments, Infra provisioning, and CV were moved to [CD and GitOps tutorials](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/category/cd-and-gitops-tutorials). These would be more useful if moved alongside related content. There is a lot going on here and it would be overwhelming as a new user.

4 tutorials were moved to platform because they demonstrate platform functionality that isn't specific to CD:
* Triggers - Moved to same location as I moved a similar CI tutorial - [Tutorial - Pipeline Triggers](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/platform/triggers/tutorial-cd-trigger) (I need to edit the title)
* Expressions - Based on google analytics and frequency of customer feedback about variables/expressions, I combined this tutorial with the existing "add a variable" topic - [Add variables](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/platform/variables-and-expressions/add-a-variable#tutorial---add-and-reference-variables-in-a-cd-pipeline)
* Notifications - Short tutorial. Combined with existing topic that was missing these useful step-by-step instructions - [Notification settings](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/platform/notifications/notification-settings)
* Templates - Short tutorial. Embedded in existing topic. - [Create a pipeline template](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/platform/templates/create-pipeline-template#create-a-pipeline-template)

There were links to these tutorials in the CD docs - These links have been preserved so that a connection still exists between the CD docs and these tutorials.

## FF

[Get started with Feature Flags](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/category/get-started-with-feature-flags)

## CCM

Optimize for K8s- [Try CCM - Optimize cloud costs for Kubernetes](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/cloud-cost-management/get-started/kubernetes)
Autostopping (7) - [AutoStopping guides](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/category/autostopping-guides)

## SRM

[Tutorial - Manage SLOs using Prometheus metrics](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/service-reliability-management/get-started/slo-prometheus)

## STO

[STO tutorials](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/category/sto-tutorials)

## CE

Your first chaos experiment - [CE onboarding guide](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/category/ce-onboarding-guide)
Chaos experiment from blank - [CE onboarding guide](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/category/ce-onboarding-guide)
Chaos experiment with API - [Run chaos experiments with APIs](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/chaos-engineering/configure-chaos-experiments/experiments/construct-and-run-custom-chaos-experiments#run-chaos-experiments-with-apis)
Gitlab pipeline - [Run chaos experiments as GitLab pipelines](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/chaos-engineering/configure-chaos-experiments/experiments/construct-and-run-custom-chaos-experiments#run-chaos-experiments-as-gitlab-pipelines)
Jenkins pipeline -  [Run chaos experiments as Jenkins pipelines](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/chaos-engineering/configure-chaos-experiments/experiments/construct-and-run-custom-chaos-experiments#run-chaos-experiments-as-jenkins-pipelines)
Integrate with CD - [Use HCE with Continuous Delivery](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/chaos-engineering/integrations/chaos-cd)

## SSCA

"Generate SBOM and enforce policies" and "Generate and verify SLSA provenance" were duplicates of existing pages. I  wrote them initially. I removed them since they were duplicates and one of them was outdated.

Automate SBOM drift detection - [Automate SBOM drift detection for GitHub repositories](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/software-supply-chain-assurance/sbom/automate-sbom-drift-detection)

## CET

[Demo - Find and fix Java exceptions](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/continuous-error-tracking/get-started/java-error-tracking)

## IDP

[IDP tutorials](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/category/idp-tutorials)

## SEI

[Insights](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/category/insights)

## Platform

Delegate tutorials (4) - Moved or combined with existing topics - [Install delegates](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/category/install-delegates)
Onboard with Terraform Provider - [Onboard with Terraform Provider](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/platform/automation/terraform/onboard-terraform-provider)
Use secrets managers - [Add a secret manager](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/platform/secrets/secrets-management/add-secrets-manager)

## SMP

Disaster recovery tutorial - [Set up disaster recovery](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/self-managed-enterprise-edition/advanced-configurations/set-up-disaster-recovery)
External DB tutorials - [External databases](https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/docs/category/external-databases)

## Other changes

- Housekeeping - Link updates
- Syntax stuff if I noticed it.
- Style guide compliance if I noticed it and had time to address it.
- Dismantle tutorial architecture and remove it from nav
- Change homepage from "get started with tutorials" to "get started"

### CODE REVIEW

**Comment by jenniferopal** [comment]
From Feature Flags, I didn't find any errors or concerns about the changes made so LGTM! Thanks, April!

**Comment by Debanitrkl** [comment]
It's getting very difficult to review with such large diffs, it's taking a lot of time to load. I think we should let the module owners to merge their tutorials into docs, so that the PR size is small.

**Review by Debanitrkl — APPROVED** [review]
LGTM for IDP

**Comment by ravilach** [comment]
Running DLC against https://65d4da46424d51008cbe4a9a--harness-developer.netlify.app/.

**Review by ravilach — APPROVED** [review]
LGTM

**Pull request merged**
