### PR TITLE
HDH-293-create-custom-page-for-refernce-architectures

### PR DESCRIPTION
**Pull request by rohanmaharjan100**
Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__
image
________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

### CODE REVIEW

**Comment by rohanmaharjan100** [comment]
@ravilach Not sure why`  reference-architecture/index.md`  is shown on sidebar and DocCard

**Comment by ravilach** [comment]
Thanks for creating @rohanmaharjan100! Like the other landing pages, can we move the Hero image to the top?

Hmm maybe it's the file name/DS ID that is duplicating the index file in the left nav?

**Comment by ravilach** [comment]
@rohanmaharjan100 if you take a look at another example e.g the CD Docs Landing:

https://raw.githubusercontent.com/harness/developer-hub/main/docs/continuous-delivery.md

The Title is different `title: Continuous Delivery & GitOps Documentation` then can link to the ID in the Sidebar.

https://github.com/harness/developer-hub/blob/main/sidebars.js#L469

Also can we rename index.md to "reference-architecture.md" please? 

Thanks!

**Comment by ravilach** [comment]
LGTM!

**Review by ravilach — APPROVED** [review]

**Review by ravilach — APPROVED** [review]

**Pull request merged**
