### PR TITLE
Update windows custom image info note.

### PR DESCRIPTION
**Pull request by dewan-ahmed**
This PR updates [this page](https://developer.harness.io/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure/#configure-cluster-and-build-infrastructure) based on [this discussion](https://harness.slack.com/archives/C013KJMDV0U/p1720417463172819).

[JIRA](https://harness.atlassian.net/browse/CI-13352)

[Preview Link](https://668e9fa0cfb6d12309c1458a--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure)

### CODE REVIEW

**Comment by dewan-ahmed** [comment]
Hi @devkimittal @nofarblue a nudge on this PR 👀

**Comment by dewan-ahmed** [comment]
Hi @devkimittal @nofarblue a nudge

**Comment by dewan-ahmed** [comment]
@lkilpatrick-harness could you please review and approve?

**Review by lkilpatrick-harness — APPROVED** [review]
The line has been removed per the request. Looks good to me.

**Pull request merged**
