### PR TITLE
Added 2 tiles to feature flag tutorials landing page

### PR DESCRIPTION
**Pull request by HarnessTheChaos**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x ] Tested Locally
- [ x] *Optional* Screen Shoot. 
image

### CODE REVIEW

**Comment by ravilach** [comment]
Thanks @HarnessTheChaos. Maybe this one is ahead of your first tutorial? E.g the source might not be in the branch as of yet?

Build output:

```
 On source page path = /tutorials/:

   -> linking to /tutorials/feature-flags/mobile-browser-refresh


- On source page path = /tutorials/feature-flags:

   -> linking to /tutorials/feature-flags/mobile-browser-refresh

```

**Comment by StrawberryPad** [comment]
@HarnessTheChaos please finish the [original PR ](https://github.com/harness/developer-hub/pull/2552#)so we can merge this one. Let me know if you're done with the original one and I can merge it.

**Comment by StrawberryPad** [comment]
> @HarnessTheChaos I went ahead and made edits to the [original PR ](https://github.com/harness/developer-hub/pull/2552#)so we can merge this one. Let me know if you're happy with it and I can merge it, before merging this one.

I went ahead and merged the original PR. You'll need to pull in 'main' into your fork to fix the broken links.

**Comment by ravilach** [comment]
@HarnessTheChaos looked fine to me. Will merge.

**Pull request merged**
