### PR TITLE
[DOC-2951] - Drone plugins

### PR DESCRIPTION
**Pull request by aimurphy**
- New custom plugins topic: https://64777c1a3a8ddb007fa82e4e--harness-developer.netlify.app/docs/continuous-integration/use-ci/use-drone-plugins/custom_plugins
- Refresh Use a Drone plugin topic: https://64777c1a3a8ddb007fa82e4e--harness-developer.netlify.app/docs/continuous-integration/use-ci/use-drone-plugins/run-a-drone-plugin-in-ci 
- Remove outdated Drone & Harness topic.
- Rearrange the plugins topics: https://64777c1a3a8ddb007fa82e4e--harness-developer.netlify.app/docs/category/use-plugins
- Minor changes and general improvements to other topics as related to the above.

### CODE REVIEW

**Comment by aimurphy** [comment]
@shubham149 @bradrydzewski Please review the new topic on writing custom plugins.

**Comment by shubham149** [comment]
I think custom plugin doc is not helpful. Refer to this blog: https://www.harness.io/blog/write-first-plugin-for-cie

**Comment by aimurphy** [comment]
@shubham149 I have made some revisions to the intro of the custom plugin topic. Please let me know if it's good to go? https://64777c1a3a8ddb007fa82e4e--harness-developer.netlify.app/docs/continuous-integration/use-ci/use-drone-plugins/custom_plugins

**Comment by aimurphy** [comment]
tech review approval given on Slack

**Review by StrawberryPad — APPROVED** [review]
Very nice, just a couple of suggestions, possible typo.

**Pull request merged**
