### PR TITLE
[DOC-3120] Add partial, sync content for SMP supported platform, features, integrations

### PR DESCRIPTION
**Pull request by brian-f-harness**
Add partial, sync content for SMP supported platform, features, integrations

For reviewers, previews are available:
Get started with Harness - [Supported platforms and technologies](http://localhost:3004/docs/getting-started/supported-platforms-and-technologies#harness-self-managed-enterprise-edition)
Self-Managed Enterprise Edition - [Supported features and integrations](https://6466b53ae70ca10c4dd35dc1--harness-developer.netlify.app/docs/self-managed-enterprise-edition/introduction/supported-features-and-integrations)

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Review by pratmit — COMMENTED** [review]
Suggested changes

**Review by pratmit — COMMENTED** [review]
Removed auto restart feature

**Review by pratmit — APPROVED** [review]
LGTM

**Comment by brian-f-harness** [comment]
Closing in favor of https://github.com/harness/developer-hub/pull/1799

**Pull request closed without merging**
