### PR TITLE
Add future roadmap for CD

### PR DESCRIPTION
**Pull request by krishi0408**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Review by prasadsatamharness — APPROVED** [review]

**Comment by ravilach** [comment]
Looks good, maybe we can add descriptions 

image

**Review by prasadsatamharness — APPROVED** [review]

**Comment by ravilach** [comment]
I feel this is good, since the page is still a work-in-progress and this would be the first rendition. Not linked to nav as of yet.Feel free to merge.

**Comment by krishi0408** [comment]
> I feel this is good, since the page is still a work-in-progress and this would be the first rendition. Not linked to nav as of yet.Feel free to merge.


Sure thanks @ravilach

**Comment by ravilach** [comment]
Looking between the two commits, CD was removed for Platform @krishi0408?

**Comment by ravilach** [comment]
Re-read, the CD Items in the original commit moved to platform.

**Pull request merged**
