### PR TITLE
CHAOS-2014: Add docs for all vmware chaos experiments

### PR DESCRIPTION
**Pull request by uditgaurav**
Waiting for some missing diagrams from Joyce.

### CODE REVIEW

**Comment by StrawberryPad** [comment]
@uditgaurav are you waiting for Joyce to do this missing image:
`error: Image docs/chaos-engineering/technical-reference/chaos-faults/vmware/static/images/**vmware-windows-disk-stress.png** used in docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-disk-stress.md not found.`

**Comment by uditgaurav** [comment]
Hi @StrawberryPad , Yes Waiting on Joyce for the diagrams.

**Comment by KimberlyFields** [comment]
@uditgaurav are you still waiting for diagrams for this PR? Also, the preview build failed on this.

**Comment by uditgaurav** [comment]
Hi @KimberlyFields , I have updated the experiment docs with diagrams and also fixed the build issues. Good to review now. Thanks!

**Comment by KimberlyFields** [comment]
Thanks, @uditgaurav. I'll review it. The preview build is still failing due to this:

Exhaustive list of all broken links found:

- On source page path = /docs/chaos-engineering/technical-reference/chaos-faults/vmware/:
   -> linking to vmware-windows-disk-fill/ (resolved as: /docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-disk-fill/)

**Comment by uditgaurav** [comment]
Ah! Thanks @KimberlyFields for pointing that out, it is fixed now.

**Comment by uditgaurav** [comment]
The PR was updated, waiting for the review on this. cc: @KimberlyFields

**Review by KimberlyFields — APPROVED** [review]

**Pull request merged**
