### PR TITLE
Added Ideas Portal to Footer

### PR DESCRIPTION
**Pull request by ravilach**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [x] *Optional* Screen Shoot. 

image

### CODE REVIEW

**Comment by ravilach** [comment]
@wei-harness @rohanmaharjan100 I forget can't remember how we suppressed the external arrow-box in CSS. Any idea?

image

**Comment by ravilach** [comment]
@rohanmaharjan100 @wei-harness can we look at this please?

**Comment by wei-harness** [comment]
@ravilach we could use `to` instead of `href` here for the new footer link

**Comment by ravilach** [comment]
Ah thanks @wei-harness!

**Pull request merged**
