### PR TITLE
feat/HDH-95

### PR DESCRIPTION
**Pull request by wei-harness**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [x] *Optional* Screen Shoot. 
Screen Shot 2023-04-05 at 6 01 46 PM

### CODE REVIEW

**Comment by wei-harness** [comment]
The urls would be like:

- /certifications/?lvl=developer
- /certifications/?lvl=administrator
- /certifications/?lvl=architect

**Comment by wei-harness** [comment]
Also hid the number of Certs in the Cards if "numberOfCerts" was not specified.

**Comment by ravilach** [comment]
Great solution @wei-harness. Hmm though when clicking on https://642dadaf47a4460fca964c4f--harness-developer.netlify.app/certifications/continuous-integration/?lvl=architect, does not bring up the Arch Tab. Not sure if there is a way to enable that.

**Comment by wei-harness** [comment]
> Great solution @wei-harness. Hmm though when clicking on https://642dadaf47a4460fca964c4f--harness-developer.netlify.app/certifications/continuous-integration/?lvl=architect, does not bring up the Arch Tab. Not sure if there is a way to enable that.

Should be fixed now.

**Review by ravilach — APPROVED** [review]

**Pull request merged**
