### PR TITLE
Updated the tutorial with the new set of commands

### PR DESCRIPTION
**Pull request by pratmit**
Updated the commands for Helm, Terraform, Docker and K8s manifest.

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Review by ravilach — APPROVED** [review]
LGTM. Are you sure you want to put tokens in there?

**Comment by pratmit** [comment]
@kat-enos Can you help me merge this?

**Comment by pratmit** [comment]
Closing this, will raise a new one with the changes.

**Comment by kat-enos** [comment]
Ping me when you want to re-open this issue. I try to push through small changes of great customer benefit quickly.

**Pull request closed without merging**
