### PR TITLE
CI Tutorial Unification

### PR DESCRIPTION
**Pull request by aimurphy**
Based on feedback from various sources, the split between Tutorials and Documentation is causing confusion. Users who find tutorials before documentation mistakenly believe the tutorials represent the full scope of CI capabilities. Users who find documentation without tutorials miss out on valuable instruction provided by those tutorials (particularly the language guides).

This project was requested by Product. Please contact me if you have concerns.

This project includes only CI tutorials and documentation.

This project included the changes described below, as well are various maintenance, rewriting, and reorganization tasks encountered in its execution. Please contact me if you have questions about a particular change. **I will remove all reviewers who were included only for links or other minor maintenance.**

## Preview link

https://65b2f24a7f893a4d0ca4ebb3--harness-developer.netlify.app/tutorials/ci-pipelines

## Changes to tutorial pages

* CI tutorials landing page: Replaced **Tutorials** button with **Documentation**. Removed **All Tutorials** section. Updated **Featured Tutorials** to **Featured Documentation**, and included 4 cards linking to 3 key tutorials and "all documentation".
* Main tutorial landing page: The list of CI tutorials is the same as the "featured documentation" on the CI tutorials landing page.
* _Harness CI overview_ and _Publish artifacts overview_: Removed these two "overview" topics in the CI tutorials that were replicas of existing documentation topics.
* _Fastest CI tutorial_: Moved to CI documentation > get started. This replaces the "Tutorials" topic there.
* _Build on K8s_: Moved to CI documentation > use ci > set up build infra > set up k8s cluster build infra.
* _Build application code_: All language guides moved to CI documentation > Development guides.
* _Terraform notification tutorial_: Moved to Platform documentation > triggers.
* _CodeCov tutorial_: Moved to Ci documentation > Use CI > Run tests > Code Coverage
* _LocalStack tutorial_ and _Sauce Connect Proxy tutorial_: Moved to CI docs > Use CI > Manage dependencies
* _Test a FastAPI project tutorial_: Moved to CI docs > use CI > Run tests
* _Google GAR tutorial_: Removed the GAR tutorial because we now have a built-in Build and Push to GAR step.
* _Publish anything to the Artifacts tab_: Moved to CI docs > use CI > Build and upload artifacts (NOTE: I have an additional reorg project planned for the Build and Upload Artifacts section)
* CI Docs landing page: Changed tutorials button to link to the main tutorials landing page. Removed the tutorials tile.
* _OIDC with GCP WIF tutorial_: Moved from the Platform tutorials to CI Docs > Secure CI. This tutorial was in the Platform section but, currently, OIDC for GCP connectors is only available for Harness Cloud.

## Other changes

This list includes maintenance changes and changes that weren't specific to tutorial topics.

* Redirects & link updates for all moved topics and removed folders, subfolders.
* Mobile development topic: Moved into Development guides section.
* Run DinD in a Background step: Moved to Manage Dependencies section because this is primarily about running DinD in a Background step/as a dependency.
* CI Run step settings topic promoted up one level due to being the only topic left in that folder.
* Renamed the security hardening topic so it won't have the same name as its parent.
* CI docs landing page: Added a tile for Development guides.
* Removed unused images and partials in CI documentation.
* Minor reorg to the caching/data sharing summary topic to better describe the available options.

### CODE REVIEW

**Comment by ravilach** [comment]
This is a pretty big change, we should discuss since CI will now look different from the other sections of HDH.

**Comment by aimurphy** [comment]
> This is a pretty big change, we should discuss since CI will now look different from the other sections of HDH.

Could you clarify which elements are substantially different, besides "Set up CI pipelines" having no nested content?

I did not remove the CI tutorials landing page, so landing page look & feel is the same. Just no content beneath.

* New CI landing page: https://65b2f24a7f893a4d0ca4ebb3--harness-developer.netlify.app/tutorials/ci-pipelines
* Compare with CD landing page: https://65b2f24a7f893a4d0ca4ebb3--harness-developer.netlify.app/tutorials/cd-pipelines 

CI is also still on the All tutorials page: https://65b2f24a7f893a4d0ca4ebb3--harness-developer.netlify.app/tutorials/

**Review by ravilach — CHANGES_REQUESTED** [review]
Can chat on Slack about traffic changes/analysis and design consistency to see how to achieve.

**Review by ravilach — DISMISSED** [review]
LGTM, with what we talked about on Zoom.

**Review by ravilach — APPROVED** [review]

**Pull request merged**
