### PR TITLE
[DOC-3308] - Output variables with secrets

### PR DESCRIPTION
**Pull request by aimurphy**
add a note for output variables where the value is a secret

https://649c4d708177fe28b66b018d--harness-developer.netlify.app/docs/continuous-integration/use-ci/run-ci-scripts/run-step-settings#output-variables

image

### CODE REVIEW

**Comment by spangler-harness** [comment]
Minor review/modification at the request of @rustd.

If your output variables value contains a secret, be aware that the secret will be visible in both the Output tab of the step where the output variable originates and in the build logs for any later steps that reference that variable.

**Comment by rustd** [comment]
@aimurphy @rajatharanganath We should also add a recommendation on how to use secrets in a pipeline. You can link to an existing document.

**Comment by aimurphy** [comment]
> @aimurphy @rajatharanganath We should also add a recommendation on how to use secrets in a pipeline. You can link to an existing document.

Do you mean like as an expression? The note already contains a link to the secrets documentation (https://developer.harness.io/docs/category/secrets). Do you want something more explicit?

**Comment by rustd** [comment]
@aimurphy something like this. Please feel to edit as needed.
If your output variables value contains a secret, be aware that the secret will be visible in both the Output tab of the step where the output variable originates and in the build logs for any later steps that reference that variable. See this (https://64947505681c054dcd296647--harness-developer.netlify.app/docs/category/secrets/) guide for best practices on using a secret in a pipeline

**Comment by aimurphy** [comment]
@rustd Here is the latest: 
image

**Review by douglas-j-bothwell — APPROVED** [review]

**Pull request merged**
