### PR TITLE
(Update): CI_ENABLE_BASE_IMAGE_DOCKER_CONNECTOR

### PR DESCRIPTION
**Pull request by KinnonYee-harness**
Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \_____. Add CI_ENABLE_BASE_IMAGE_DOCKER_CONNECTOR information for Base Image to Connector information
* Jira/GitHub Issue numbers (if any): \______. https://harnesssupport.zendesk.com/agent/tickets/69939
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

### CODE REVIEW

**Comment by bot2-harness** [comment]
This pull request has been automatically closed due to 30 days of inactivity. If you believe this was done in error, please feel free to reopen the PR or reach out to the BT team for further assistance. Thank you for your contributions!

**Review by dewan-ahmed — APPROVED** [review]
LGTM

**Comment by dewan-ahmed** [comment]
This needs a review from PL CODEOWNERs.

**Comment by KinnonYee-harness** [comment]
FYI @krishi0408, please review

**Comment by pratmit** [comment]
This will require review from CI team as it is a CI FF.

**Comment by KinnonYee-harness** [comment]
@nofarblue Can you please review and merge?  Thanks

**Comment by dewan-ahmed** [comment]
The actual path of the changed file is `docs/platform/connectors/cloud-providers/ref-cloud-providers/docker-registry-connector-settings-reference.md` so a platform CODEOWNER needs to review before this PR can be merged. @nofarblue can check from the SME point for the FF.

**Comment by bot2-harness** [comment]
This pull request has been automatically closed due to 30 days of inactivity. If you believe this was done in error, please feel free to reopen the PR or reach out to the BT team for further assistance. Thank you for your contributions!

**Comment by KinnonYee-harness** [comment]
@nofarblue @nofarb Can you please review and merge?  Thank you

**Review by krishi0408 — APPROVED** [review]

**Pull request merged**
