### PR TITLE
[SMP-1584] Update air gap docs with module file info

### PR DESCRIPTION
**Pull request by brian-f-harness**
Update air gap docs with module file info

For reviewers, [a preview](https://64a706c72224d3667d8170fa--harness-developer.netlify.app/docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-an-air-gapped-environment) is available.

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Review by pratmit — DISMISSED** [review]

**Comment by swapnil-harness** [comment]
Edit this hyperlink 
https://console.cloud.google.com/storage/browser/smp-airgap-bundles;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false&pli=1
With 
https://console.cloud.google.com/storage/browser/smp-airgap-bundles

**Comment by swapnil-harness** [comment]
Edit this command 
./harness-airgap-images.sh -r <REGISTRY.YOURDOMAIN.COM:PORT> -f harness-airgapped.tgz
With
./harness-airgap-images.sh -r <REGISTRY.YOURDOMAIN.COM:PORT> -f <moduleName-images.tgz>

**Comment by swapnil-harness** [comment]
Replace <harness-docker-images.txt> from here 

All Docker files required to deploy Harness are stored in the [Harness air gap image bundle](https://console.cloud.google.com/storage/browser/smp-airgap-bundles;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false&pli=1) in the harness-docker-images.txt file.

TO:
https://github.com/harness/helm-charts/releases

**Comment by swapnil-harness** [comment]
Please edit this step:
Add the *.tgz for each module you want to deploy and the harness-docker-images.txt file to your air-gapped network. You can now push your images locally.

TO:
Add the *.tgz for each module you want to deploy to your air-gapped network. You can now push images locally.

**Review by swapnil-harness — APPROVED** [review]
LGTM! Thanks!

**Review by douglas-j-bothwell — APPROVED** [review]

**Pull request merged**
