### PR TITLE
fixed redirect file generation

### PR DESCRIPTION
**Pull request by rohanmaharjan100**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [
image
image
image
 ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by wei-harness** [comment]
@ravilach preview redirects:

- https://64d4c11c54f15b56d8efa70e--harness-developer.netlify.app/helm/
- https://64d4c11c54f15b56d8efa70e--harness-developer.netlify.app/faqs/
- https://64d4c11c54f15b56d8efa70e--harness-developer.netlify.app/ci-faqs/
- https://64d4c11c54f15b56d8efa70e--harness-developer.netlify.app/chart/

**Comment by wei-harness** [comment]
LGTM,
@ravilach we shall give it more test data in front matter section to well test it,
after all the tests, let's remove the test data and merge it to main.

**Comment by ravilach** [comment]
@wei-harness @rohanmaharjan100 thanks for creating! Let's chat about a roll out plan.

**Comment by rohanmaharjan100** [comment]
@wei-harness @ravilach I have merged redirect file from archives . Please check.
image

**Comment by ravilach** [comment]
Thanks! When the build finishes, can go test a few.

**Comment by rohanmaharjan100** [comment]
@ravilach  @wei-harness

**Comment by rohanmaharjan100** [comment]
Hi Guys @ravilach  @wei-harness  I have re added client redirect plugin and file . Please review

**Pull request merged**
