### PR TITLE
HDH-297-add-math-packages-to-ds

### PR DESCRIPTION
**Pull request by rohanmaharjan100**
Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

### CODE REVIEW

**Comment by ravilach** [comment]
Maybe a missing page, can bring the PR up to speed e.g rebase?

**Comment by rohanmaharjan100** [comment]
Build is successful locally, not sure what the problem is .

**Comment by ravilach** [comment]
I think a re-base will solve it. Point in time maybe someone made a change to this file:

```
Error: Can't render static file for pathname "/docs/first-gen/continuous-delivery/continuous-verification/custom-metrics-and-logs-verification/verify-deployments-with-custom-metrics"
```

**Comment by rohanmaharjan100** [comment]
Hmm.. looks like `$` was the problem indeed. Thanks @ravilach

**Review by ravilach — APPROVED** [review]

**Pull request merged**
