### PR TITLE
HDH 182 investigate Dark mode

### PR DESCRIPTION
**Pull request by rohanmaharjan100**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screenshot.

### CODE REVIEW

**Comment by ravilach** [comment]
Great step in the right direction. Two minor/medium items. In Dark Mode, we do need to look at our logo since it is a black background if we want to switch to a white logo background, similar to www.harness.io. Also the video animation, @wei-harness if we need to work with the designer to make a dark mode friendly version with the rings being white or we stop the animation in dark mode for now.

image

**Comment by wei-harness** [comment]
@ravilach sure, will create sub-task for the animation and illustrations for dark mode 
cc @joannalye @valentina.inzaghidontree

**Comment by rohanmaharjan100** [comment]
@wei-harness @ravilach Navbar logo and roadmap page fix.

**Comment by ravilach** [comment]
LGTM!

**Comment by rohanmaharjan100** [comment]
@ravilach  Yes , new  homepage animation for dark mode has been added .

**Comment by ravilach** [comment]
Great! I clicked on the wrong preview link. LGTM!

**Review by ravilach — APPROVED** [review]

**Pull request merged**
