### PR TITLE
fix: [CDE]: Refactored cde to cdes in the URL path

### PR DESCRIPTION
**Pull request by Debanitrkl**
Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

### CODE REVIEW

**Review by wei-harness — COMMENTED** [review]
@Debanitrkl I noticed that for some Markdown files, you've added the `redirect_from` front matter, but for other renamed Markdown files, you didn't add. Could you review and ensure consistency across all renamed files?

**Comment by Debanitrkl** [comment]
> @Debanitrkl I noticed that for some Markdown files, you've added the redirect_from front matter, but for other renamed Markdown files, you didn't add. Could you review and ensure consistency across all renamed files?

I have added a server-redirect which solves for all the URL changes, those individual redirect_from aren't required anymore.

**Review by manishas — APPROVED** [review]

**Comment by wei-harness** [comment]
> > @Debanitrkl I noticed that for some Markdown files, you've added the redirect_from front matter, but for other renamed Markdown files, you didn't add. Could you review and ensure consistency across all renamed files?
> 
> I have added a server-redirect which solves for all the URL changes, those individual redirect_from aren't required anymore.
@Debanitrkl ,
Did you mean line #76 in `_server_redirect` ? 
`/docs/cloud-development-environment /docs/cloud-development-environments `
------
that one only redirect the single path `/docs/cloud-development-environment`, but not all the recursive paths ( `/docs/cloud-development-environment/**` )
you can try out with the preview link: https://67075cd3fb46d95e5b9d8d31--harness-developer.netlify.app/docs/cloud-development-environment/develop-using-cde/forward-ports

**Comment by Debanitrkl** [comment]
> that one only redirect the single path /docs/cloud-development-environment, but not all the recursive paths ( /docs/cloud-development-environment/** )

Yes that's why I added redirects for the pages which would have been shared previously, this being a new module the docs hasn't been widely shared yet so we are good with not having redirects for each individual docs page.

**Comment by Debanitrkl** [comment]
> that one only redirect the single path /docs/cloud-development-environment, but not all the recursive paths ( /docs/cloud-development-environment/** )

Yes that's why I added redirects for the pages which would have been shared previously, this being a new module the docs hasn't been widely shared yet so we are good with not having redirects for each individual docs page.

**Pull request merged**
