### PR TITLE
add .gitleaksignore and seed with a secret

### PR DESCRIPTION
**Pull request by ChrisHam8066**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot. 

This PR adds a .gitleaksignore file and seeds it with a sample fingerprint.

### CODE REVIEW

**Comment by KimberlyFields** [comment]
@ravilach and @ChrisHam8066 please review and approve this PR if it looks correct. I added all of the leaks that Chris found. Most were in docs, but a few were in docusaurus config files and coveosearch.js files.

**Comment by ravilach** [comment]
@KimberlyFields I'm unfamiliar with GitLeaks as a provider. I see no issue committing the config file as has no impact on build CC @ChrisHam8066.

**Comment by ravilach** [comment]
Looks like @ChrisHam8066 covered the DS ones. Thanks! https://github.com/harness/developer-hub/pull/2873/files#diff-923efe99d6c7d5214835596b604a975bd0cdb77a0407b214ea308a97ea7b55dbR128

**Review by ravilach — APPROVED** [review]

**Comment by ravilach** [comment]
Approved on my side. Would we like to merge @ChrisHam8066 / @KimberlyFields?

**Comment by ChrisHam8066** [comment]
there are 2 remaining secrets we can add through separate PR.

**Pull request merged**
