### PR TITLE
Update self-managed-enterprise-edition-architecture.md

### PR DESCRIPTION
**Pull request by pratmit**
We don't support VM configuration anymore.

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Review by brian-f-harness — COMMENTED** [review]
Do we need to remove lines 21 to 27 as well, or do they still apply?

**Comment by pratmit** [comment]
Good call, we should remove lines 21 to 24 as well for now.

**Comment by brian-f-harness** [comment]
> Good call, we should remove lines 21 to 24 as well for now.

Ok. Thank you @pratmit. Just to clarify, do lines 25-27 still apply, or do we need to remove 21-27?

**Comment by pratmit** [comment]
25 - 27 still apply.

**Comment by pratmit** [comment]
I mean that covers the kubernetes installation option.

**Review by brian-f-harness — APPROVED** [review]

**Pull request merged**
