### PR TITLE
Added Azure Infrastructure Provisioning for Harness Delegate tutorial

### PR DESCRIPTION
**Pull request by codewdhruv**
Added first draft of **Provisioning Azure Infrastructure for Harness Delegate** Tutorial.
Following the style conventions to ensure a consistent user experience.
Signed-off-by: Dhrubajyoti C [dhrubajyoti.chakraborty@harness.io](mailto:dhrubajyoti.chakraborty@harness.io)

**Screenshots:**

Screenshot 2022-12-19 at 8 57 02 PM

### CODE REVIEW

**Comment by KimberlyFields** [comment]
@kat-enos please provide an editorial review. Thanks.

**Comment by ravilach** [comment]
@codewdhruv thanks for the contribution, mind creating two elements in the Platform and All Tutorial Sections for your stuff? 

All:
https://github.com/harness/developer-hub/blob/main/src/components/LandingPage/AllTutorials.tsx

Platform:
https://github.com/harness/developer-hub/blob/main/src/components/LandingPage/Platform.tsx

Cheers,

-Ravi

**Comment by codewdhruv** [comment]
Updated elements at [AllTutorials.tsx](https://github.com/harness/developer-hub/blob/main/src/components/LandingPage/AllTutorials.tsx) & [Platform.tsx](https://github.com/harness/developer-hub/blob/main/src/components/LandingPage/Platform.tsx)

Tested the build locally. No errors. cc: @ravilach

**Comment by ravilach** [comment]
Thanks @codewdhruv! Looks good from my side. Just need a review from @kat-enos and we are good to go. Heads up any suggestions please bulk-commit/accept. Each commit to the PR is a build :-)

**Comment by ravilach** [comment]
Looks good to me. Will merge post PR build with @kat-enos's edits. Congrats on being published, @codewdhruv!

**Comment by ravilach** [comment]
Just my luck, @wei-harness dropped another plug-in for our image resizing. @codewdhruv can you re-base your branch [the yarn.lock has merge conflicts] and re-base?

**Comment by ravilach** [comment]
Merging. Thanks for the help @wei-harness and @kat-enos. Looked like the Merge Conflict maybe was from the IDE formatting a few lines in the yarn lock. @codewdhruv. We are all set.

**Comment by codewdhruv** [comment]
Thanks.

**Pull request merged**
