### PR TITLE
[SMP-1614] SMP v79421 patch release notes

### PR DESCRIPTION
**Pull request by brian-f-harness**
SMP v79421 patch release notes

For reviewers, previews are available:

[CG](https://64a89e0d7ed34f22502eaeaf--harness-developer.netlify.app/docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes)
[NG](https://64a89e0d7ed34f22502eaeaf--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition#july-7-2023-patch-release-for-version-79421)

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by swapnil-harness** [comment]
NG link is pointing to June 30th release

**Comment by brian-f-harness** [comment]
> NG link is pointing to June 30th release [NG](https://64a88d395489341c9976a3af--harness-developer.netlify.app/release-notes/self-managed-enterprise-edition)

@swapnil-harness  The patch release notes are available on the NG preview under the Patch release tab. I'm not able to link to the tab for the preview.

**Review by swapnil-harness — DISMISSED** [review]
LGTM! Thanks!

**Review by pratmit — DISMISSED** [review]
LGTM

**Review by aimurphy — APPROVED** [review]

**Pull request merged**
