### PR TITLE
[SMP-1029] Add SMP external database topic

### PR DESCRIPTION
**Pull request by brian-f-harness**
Adds an SMP external database topic. I will add the diagrams from the doc in phase 2 (SMP-1269).

For reviewers, [a preview](https://64623416b5c7dd196fcecbcd--harness-developer.netlify.app/docs/self-managed-enterprise-edition/introduction/supported-features-and-integrations) is available.

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by pratmit** [comment]
This need to be hold off. There is a bug post which we should update the workflow - https://harness.atlassian.net/browse/SMP-1278

**Comment by arya-harness** [comment]
Do we think it would good to add the helm configuration changes in this doc on how to enable external mongo. (Maybe we could provide a hyperlink to it)

**Comment by arya-harness** [comment]
We could add the notes from this ticket: https://harness.atlassian.net/browse/SMP-1274

**Comment by brian-f-harness** [comment]
> We could add the notes from this ticket: https://harness.atlassian.net/browse/SMP-1274

Thank you @arya-harness. I added the details. I will update the doc preview when the docs build finishes.

**Review by arya-harness — APPROVED** [review]

**Review by akshay-khole — APPROVED** [review]
we can update document with version change once we have confirmation

**Review by douglas-j-bothwell — APPROVED** [review]

**Pull request merged**
