### PR TITLE
chore: add social card image [HDH-171]

### PR DESCRIPTION
**Pull request by wei-harness**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [x] *Optional* Screen Shoot. 

hdh-social-card

### CODE REVIEW

**Comment by wei-harness** [comment]
Preview: https://64d54701fc0fb5094b2a80c9--harness-developer.netlify.app

Screen Shot 2023-08-10 at 9 26 36 PM

**Comment by ravilach** [comment]
Thanks @wei-harness. Is there one without "Read the Blog" as we have multiple content types.

**Comment by wei-harness** [comment]
Button removed @ravilach 

hdh-social-card

**Comment by ravilach** [comment]
LGTM!

**Review by ravilach — APPROVED** [review]

**Pull request merged**
