### PR TITLE
FAQ creation for Certs 

### PR DESCRIPTION
**Pull request by KMarquart89**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by KMarquart89** [comment]
@ravilach

**Comment by ravilach** [comment]
@KMarquart89 here is the build output, can check the link of the IMGs. Also, can we rename to "faqs"? Thanks!

Image Links: Can see https://raw.githubusercontent.com/harness/developer-hub/main/certifications/instructions.md

```
(./static/instruqt-screen.png)
```

```
Error: Image certifications/certifications/static/loading-error.png used in certifications/faq.md not found.

    at async Promise.all (index 0)
```

**Comment by KMarquart89** [comment]
@ravilach Fixed- try now.

**Comment by ravilach** [comment]
Hmm don't see the page show up on: https://64ee264f25b5bb02586c61c3--harness-developer.netlify.app/certifications/

Getting close, can add a link in `sidebar-certificaitons.js` on the root of the directory?

image

```
         // FAQs
         {
          type: "doc",
          label: "FAQs",
          id: "faqs",
        },
```

**Pull request merged**
