### PR TITLE
KB - Delegate Installation Error in GKE

### PR DESCRIPTION
**Pull request by codewdhruv**
Signed-off-by: Dhrubajyoti Chakraborty [dhrubajyoti.chakraborty@harness.io](mailto:dhrubajyoti.chakraborty@harness.io)

## Summary

This PR contains the Knowledge Base article on [“How Can I Fix The Delegate Installation Error in GKE?"](https://community.harness.io/t/how-can-i-fix-the-delegate-installation-error-in-gke/12870/1)

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore
- [x] KB article

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping

- [x] Tested Locally

### CODE REVIEW

**Comment by ravilach** [comment]
@codewdhruv can you move under platform kb? https://developer.harness.io/kb/platform

Maybe a quick addition to the title around the readiness probe?

Thanks!

**Comment by ravilach** [comment]
Thanks. Sorry one more [or a pair] of comments and we are good to go @codewdhruv .

Can you remove this file? This is a place holder since you are the first  to publish there. 
https://github.com/harness/developer-hub/blob/main/kb/platform/troubleshooting-guide.md

Second, if you want, can add to this list:

image

```
src/components/KnowledgeBase/LandingPage
```

https://github.com/harness/developer-hub/blob/main/src/components/KnowledgeBase/data/knowledgeBaseData.ts

```
  {
    title: "Build and Push to ECR Permission Troubleshooting",
    module: MODULES.ci,
    date: "March 30, 2023",
    link: "/kb/continuous-integration/delegate_eks_cluster",
  },
```

**Comment by codewdhruv** [comment]
@ravilach added article route to knowledgeBaseList.ts, modified the module: platform & deleted the troubleshooting file. Thanks.

**Comment by ravilach** [comment]
Not sure why there is a merge conflict, hmm can you grant me access on your Fork?

image

**Comment by codewdhruv** [comment]
@ravilach access given. Thanks.

**Comment by ravilach** [comment]
Created a new PR

**Pull request closed without merging**
