### PR TITLE
Updated FAQ

### PR DESCRIPTION
**Pull request by NandeeshHarness**
Updated FAQ

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore
- [x] Tested Locally
- [ ] *Optional* Screenshot.

### CODE REVIEW

**Comment by aimurphy** [comment]
Please check the contents of this change. It looks like the entire contents of the file has been duplicated.

**Review by deepanshuHarness — APPROVED** [review]

**Comment by aimurphy** [comment]
Please don't merge this without further review.

It looks like the entire file has been duplicated again and the file now contains multiple sets of metadata and is almost 20,000 lines long.

What is the goal of this PR?

image

@ravilach @KMarquart89

**Review by aimurphy — CHANGES_REQUESTED** [review]
Please review the diff.

**Comment by NandeeshHarness** [comment]
Closing this PR to avoid the duplicate

**Pull request closed without merging**
