### PR TITLE
Update set-up-cost-visibility-for-kubernetes.md

### PR DESCRIPTION
**Pull request by rssnyder**
# Harness Developer Pull Request

This document was very confusing for users new to Harness.

I did some reorg of the sections, linked to good existing docs on deploying delegates to reduce duplication, and added some outline sections to help provide the reasons we do each steps. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by ravilach** [comment]
@charanya-j

**Comment by ravilach** [comment]
@rdsoze who is needs to review CCM changes? Thanks!

**Comment by bot2-harness** [comment]
This PR has been automatically closed due to inactivity.

**Comment by rssnyder** [comment]
@ravilach still looking for reviewers? I see there are other CCM PRS awaiting review as well.

**Comment by ravilach** [comment]
Thanks for the heads up @rssnyder. @rdsoze can you take a look at please?

**Comment by ravilach** [comment]
@rdsoze who should approve?

**Comment by aimurphy** [comment]
@jyotiarora-harness @rdsoze This PR has been open since last year. Please take action to merge it or close it.

**Comment by aimurphy** [comment]
@rdsoze Handling this on a fresh PR due to age. https://github.com/harness/developer-hub/pull/6068

**Pull request closed without merging**
