### PR TITLE
 HDH-207-create-roadmap-functionality-on-hdh

### PR DESCRIPTION
**Pull request by rohanmaharjan100**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by ravilach** [comment]
@rohanmaharjan100 build still failing

```
Error: Docusaurus server-side rendering could not render static page with path /roadmap/ because of error: document is not defined

It looks like you are using code that should run on the client-side only.
```

**Comment by ravilach** [comment]
Getting closer @rohanmaharjan100 

```
Error: Docusaurus server-side rendering could not render static page with path /roadmap/ because of error: localStorage is not defined

It looks like you are using code that should run on the client-side only
```
Can run `yarn build` locally to see also?

**Comment by rohanmaharjan100** [comment]
Takes very long to build on my machine ..so used github one for testing if the build fails.

**Review by ravilach — APPROVED** [review]

**Review by ravilach — APPROVED** [review]
LGTM

**Pull request merged**
