### PR TITLE
Prototyping a Simple Link Between Docs and Tutorial Left Navs

### PR DESCRIPTION
**Pull request by ravilach**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [x] *Optional* Screen Shoot. 

From Tutorials

image

From Docs

image

### CODE REVIEW

**Comment by ravilach** [comment]
Adjusted 

image

**Comment by ravilach** [comment]
Match left and top update 

image

**Comment by ravilach** [comment]
Removed Join Slack

image

**Comment by ravilach** [comment]
One update - https://harness.atlassian.net/browse/HDH-151

**Review by schoudhury — APPROVED** [review]

**Pull request merged**
