### PR TITLE
Article on "Build, Test, and Publish a Docker Image for a sample React application"

### PR DESCRIPTION
**Pull request by codewdhruv**
Signed-off-by: Dhrubajyoti Chakraborty [dhrubajyoti.chakraborty@harness.io](mailto:dhrubajyoti.chakraborty@harness.io)

## Summary

This PR contains an article on **Build, Test, and Publish a Docker Image for a sample React application** that helps the user to get started with a sample Harness workflow for an React application hosted under harness-community.

- Created a new folder section `ci-react-quickstart` under `./tutorials/build-code/static/` to store the static image files
- Added one file `ci-react-quickstart.md`

## What Type of PR is This?

- [x] Tutorials

## HouseKeeping
Some items to keep track of. Screenshots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [x] *Optional* Screen Shoot.
Screenshot 2023-01-09 at 1 30 52 PM

Screenshot 2023-01-09 at 1 31 11 PM

### CODE REVIEW

**Comment by ravilach** [comment]
@codewdhruv thanks for the PR. A few items.

* Can you un-commit the yarn.lock file in the root of the project?
* Can you add tiles specifically to the /src/components/landingpage -> AllTutorials.tsx and ContinuousIntegration.tsx.

As a general heads up, this one is pretty similar to The JAVA HTTP one, minus the app.

**Review by ravilach — CHANGES_REQUESTED** [review]
Changes in previous comment. 

* yarn.lock file needs to be un-committed. 
* Tiles

**Comment by codewdhruv** [comment]
changes added @ravilach

**Review by ravilach — APPROVED** [review]
From the tech side, looks good to me. Will allow time for @KimberlyFields's team to take a look at writing style.

**Review by KimberlyFields — APPROVED** [review]

**Pull request merged**
