### PR TITLE
Add error tracking tutorial

### PR DESCRIPTION
**Pull request by hirsch-harness**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by hirsch-harness** [comment]
Adding a new tutorial page for the SRM module.

**Comment by KimberlyFields** [comment]
I added Ravi as a content reviewer since he is responsible for the tutorials and Sudhi as a reviewer from the docs team to check for style, punctuation, grammar, etc.

**Comment by ravilach** [comment]
Woops, didn't realize @hirsch-harness  re-committed after we spoke Monday. Looks good on my side with the suggestions were implemented.

**Review by ravilach — APPROVED** [review]
Looks good content wise on my side.

**Comment by ravilach** [comment]
@SudheendraKatte does this look good?

**Pull request merged**
