### PR TITLE
Baseline devcontainer.json

### PR DESCRIPTION
**Pull request by tuffacton**
Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Creating a baseline devcontainer with host requirements so it will spin up in Github Codespaces with at least the Tier 2 4 CPU host (any lower and the `yarn start` will error out)
* Still working internally on Harness CDE on a Large instance
* No actual docs modification needed

### CODE REVIEW

**Comment by tuffacton** [comment]
@ravilach can I get a review? Doesn't change any HDH code, just adds a base devcontainer so we can start using it in Codespaces and CDE hopefully in the near-term after some quick product mods.

**Comment by ravilach** [comment]
Would defer to @wei-harness / @pratmit. Don't see an issue with it.

**Review by wei-harness — COMMENTED** [review]
Hi Nic, it looks very nice, and having the devcontainer configuration would certainly be convenient. 
though it still seems a bit optional. 
Could you explain more about why it’s necessary to add it publicly to the repo instead of keeping it within a smaller group?

**Comment by tuffacton** [comment]
> Hi Nic, it looks very nice, and having the devcontainer configuration would certainly be convenient. though it still seems a bit optional. Could you explain more about why it’s necessary to add it publicly to the repo instead of keeping it within a smaller group?

Every major devcontainer product/project/convention like Github Codespaces, Harness Open Source, and our new CDE product spin up devcontainers based on the devcontainer.json defined in the pulled repository in this manner. Separating the two is not possible nor is it a recommended industry standard.

This should not affect actual upstream/downstream builds as we can see our pipeline checks passed.

**Review by wei-harness — APPROVED** [review]

**Pull request merged**
